baseURL: https://co-analysis.github.io/csps2021-response-rate-tracker/
languageCode: en-gb
title: "CSPS 2021 Response Rates"
theme: govukhugo
publishDir: docs
canonifyurls: true
disableKinds: ["taxonomy", "term"]

pygmentsUseClasses: true

markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    anchorLineNos: false
    codeFences: true
    guessSyntax: false
    hl_Lines: ""
    lineAnchors: ""
    lineNoStart: 1
    lineNos: true
    lineNumbersInTable: true
    noClasses: true
    style: github
    tabWidth: 2


params:
  govuk: false
  logotext: CSPS21
  product: "Civil Service People Survey 2021 Response Rates"
  builtby: "Cabinet Office Analysis & Insight"
  builtbyurl: https://www.github.com/co-analysis
  accessibility: accessibility.md
  privacy: privacy.md
